###ekf config file ###

ekf_filter_node:
    ros__parameters:
        
        frequency: 20.0
        
        two_d_mode: true
        
        publish_acceleration: true
        
        publish_tf: true
        
        map_frame: map
        odom_frame: odom
        base_link_frame: base_footprint
        
        odom0: "odom_diff"
        odom0_config: [true,  true,  false,
                      false, false, false,
                      false, false, false,
                      false, false, false,
                      false, false, false]
        odom0_queue_size: 10
                      
        imu0: "imu"
        imu0_config: [false, false, false,
                     false, false, false,
                     false, false, false,
                     true,  true,  true,
                     true,  true,  true]
        imu0_queue_size: 10

        initial_state: [0.0, 0.0, 0.0,
                        0.0, 0.0, 0.0,
                        0.0, 0.0, 0.0,
                        0.0, 0.0, 0.0,
                        0.0, 0.0, 0.0,]